//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartments
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Apartments = new HashSet<Apartment>();
        }
    
        public int IDPerson { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "First name max length 50 chars")]

        public string FirstName { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Last anem max length 50 chars")]
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartments { get; set; }

        public String Description  => ToString();


        public override string ToString()
        {
            return FirstName + " " + LastName;
        }
    }
}
